---
title: "Treatment effect visualisation"
author: "Pujen Shrestha"
date: '2022-12-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(scipen = 999)

library(tidyverse)
library(broom)

source()
```

```{r}
generate_data <- function(rep, rep_n, mean, sd) {
  data_out <- tibble(arm = rep(rep, rep_n),
                 outcome = rnorm(rep_n, mean = mean, sd = sd)) 
  return(data_out)
}

data_1 <- generate_data("Control", 200, 7, 1.0)
data_2 <- generate_data("Treatment 1", 200, 7, 1.8)
data_3 <- generate_data("Treatment 2", 200, 8, 3.2)

data_generated <- data_1 %>% 
  rbind(data_2) %>% 
  rbind(data_3) %>% 
  mutate(arm = as.character(arm))
```

```{r}
reg_1 <- lm(outcome ~ arm, data = data_generated)

arms <- c("Treatment 1", "Treatment 2")

tidyAndMCA <- function(regression, arms) {
  regression_tidy <- tidy(regression)
  
  arms <- paste0("arm", arms)
  
  regression_tidy_adjusted <- regression_tidy %>% 
    mutate(p.value.adjusted = if_else(term %in% arms, p.adjust(p.value, method = "bonferroni"), p.value))
  
  return(regression_tidy_adjusted)
}

reg_1_tidyAndMCA <- tidyAndMCA(reg_1, arms)

```

```{r}

control_mean <- data_generated %>% 
  filter(arm == "Control") %>%
  summarise(mean = mean(outcome, na.rm = TRUE)) %>% 
  pull(mean)

arms <- paste0("arm", arms)

dataPlot <- reg_1_tidyAndMCA %>% 
  filter(term %in% arms)

dataPlot <- dataPlot %>% 
  mutate(estimate = estimate + control_mean,
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error)

dataPlot <- dataPlot %>% 
  add_row(term = "Control",
          estimate = control_mean,
          .before = 1)

dataPlot <- dataPlot %>% 
  mutate(bar_color = if_else(term == "Control", "Control", "Treatment"),
         label = as.character(round(estimate, digits = 2),
                              width = 4,
                              pad = "0",
                              side = "right"))

bar_colors <- c("blue", "grey")

ggplot() +
  geom_col(data = dataPlot, aes(x = term,
                                y = estimate,
                                fill = bar_color)) +
  scale_fill_manual(values = bar_colors) +
  geom_errorbar(data = dataPlot,
                aes(x= term, ymin=upper, ymax=lower), width=0.2, size=1, color="orange") +
  geom_text(data = dataPlot, aes(x = term,
                                y = (estimate*.9) - (if_else(is.na(std.error),0, std.error*1.96)),
                                label = label), size = 8, fontface = 2, color = "white") +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        legend.position="none",
        axis.title.x = element_blank(),
        text = element_text(size = 12)) +
  coord_cartesian(ylim=c(0,8.5), xlim=c(1, 3))

```

